"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidenav from "./sidenav";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const disableNavbar = ["/login", "/register"];
const enableClass = "h-screen w-100 items-center";
const classname = "static inline-block top-0 z-40 h-screen p-3";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={`flex ${
            disableNavbar.includes(pathname) && "justify-center items-center"
          }`}
        >
          {!disableNavbar.includes(pathname) && <Sidenav />}
          {/* <Sidenav></Sidenav> */}
          <div
            className={`${!disableNavbar.includes(pathname) && enableClass} ${
              !disableNavbar.includes(pathname) && classname
            }`}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
